#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

groups:
  - ubuntu: [root, sys]
  - backbone

packages:
  - git
  - nginx
  - certbot
  - python3-certbot-nginx
  - npm

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: backbone
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false
    ssh-authorized-keys:
      - ${pub_key}

runcmd:
  - /usr/bin/git clone https://github.com/dills122/backbone-infa.git backbone-src
  # - sudo rm -rf /etc/nginx/conf.d/* && sudo rm -rf /etc/nginx/sites-available/* # remove all default files
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  - [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  - nvm alias default lts/iron
  - sudo ufw allow 'Nginx Full'
  - sudo ufw deny 6379 # Lockdown redis port from the outside world
  - sudo wget -O /usr/local/bin/ufw-docker https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
  - sudo chmod +x /usr/local/bin/ufw-docker
  - sudo ufw-docker install
  - sudo systemctl restart ufw
  - /usr/bin/bash ./backbone-src/scripts/umami-setup.sh
  - /usr/bin/bash ./backbone-src/scripts/personal-site-setup.sh
  - sudo systemctl restart nginx
  - /usr/bin/docker update --restart unless-stopped $(docker ps -q)
  - sudo echo "0 12 * * * terraform /usr/bin/certbot renew --quiet" >/etc/cron.d/certbot_renew

final_message: "The system is finally up, after $UPTIME seconds"
